# Project 3 - ALY-6050 - Introduction to Enterprise Analytics
### Chetan Kulkarni
### Northeastern University, Silicon Valley

### Problem 1 - Description
Perform exponential smoothing forecasts on the Honeywell stock prices to forecast the price for 4/16/2018. Use successive values of 0.15, 0.35, 0.55, and 0.75 for the smoothing parameter α. Calculate the MSE of each forecast, Use the MSEs of your forecasts to determine the value of α that has provided the most accurate forecast. Describe qualitatively as to why such a value of α has yielded the most accurate forecast.

Steps:
1) Import the Honeywell data set.
2) Using the exponential smoothing technique calculate the results at different levels of alpha
3) Support the assertion by calculating the mean square error

Import Libraries

In [338]:
import warnings
import itertools
import numpy as np
import random
import pandas as pd
from scipy.stats import uniform
import math
import seaborn as sns
from matplotlib import pyplot as plt
import scipy 
from scipy.stats import chisquare
from scipy.stats import norm, chi2, expon

Read the honeywell file and write it to a dataframe

In [339]:
df = pd.read_excel("Honeywell.xlsx", header = 0, skiprows = 0)
df = pd.DataFrame(df)
df.tail()

Period       Date       Close   Volume
119     120 2018-04-09  142.830002  1952400
120     121 2018-04-10  145.630005  2880400
121     122 2018-04-11  144.279999  1953100
122     123 2018-04-12  146.470001  2327600
123     124 2018-04-13  146.119995  1588500

In [340]:
close = df['Close']
close[0]

143.75

Exponential Smoothing Formula : 

S=αyt+(1−α)St,0<α≤1,t>0

α = the smoothing constant, a value from 0 to 1. When α is close to zero, smoothing happens more slowly. Following this, the best value for α is the one that results in the smallest mean squared error (MSE). Various ways exist to do this, but a popular method is the Levenberg–Marquardt algorithm. Here, t = time period.

Based on the formula, we have calcuated the results.

In [341]:
def exponential_smoothing(close, alpha):
    """given a close and alpha, return close of expoentially smoothed points"""
    results = np.zeros_like(close)
    # first value remains the same as close
    results[0] = close[0] 
    for i in range(1, close.shape[0]):
        results[i] = round(alpha * close[i] + (1 - alpha) * results[i - 1], 2)
    return results

In [342]:
exponential_smoothing(close.values, 0.15)

array([143.75, 143.7 , 143.66, 143.65, 143.91, 144.21, 144.5 , 144.72,
       144.89, 145.09, 145.02, 144.89, 144.9 , 144.98, 144.98, 145.07,
       145.36, 145.59, 145.57, 145.6 , 145.77, 146.  , 146.06, 146.18,
       146.23, 146.49, 146.92, 147.23, 147.59, 148.02, 148.73, 149.41,
       150.39, 150.99, 151.41, 151.66, 151.86, 152.07, 152.31, 152.45,
       152.64, 153.11, 153.13, 153.3 , 153.49, 153.58, 153.75, 153.75,
       153.71, 153.72, 153.75, 153.81, 153.74, 153.74, 153.55, 153.69,
       153.97, 154.09, 154.38, 154.79, 155.26, 155.83, 156.14, 156.48,
       156.67, 156.97, 157.21, 157.57, 157.93, 158.52, 159.49, 159.79,
       159.67, 159.67, 159.67, 159.22, 157.86, 156.89, 156.04, 154.54,
       153.54, 152.93, 152.27, 151.99, 152.2 , 152.47, 152.75, 152.95,
       153.  , 153.32, 153.8 , 153.82, 153.41, 152.48, 151.83, 151.33,
       151.03, 150.94, 150.98, 151.46, 151.58, 151.57, 151.4 , 151.35,
       151.41, 151.23, 151.12, 151.16, 150.52, 149.43, 149.06, 148.35,
      

In [343]:
df['smoothing@0.15'] = exponential_smoothing(close.values, 0.15)
df['smoothing@0.35'] = exponential_smoothing(close.values, 0.35)
df['smoothing@0.55'] = exponential_smoothing(close.values, 0.55)
df['smoothing@0.75'] = exponential_smoothing(close.values, 0.75)

In [344]:
df.head()

Period       Date       Close   Volume  smoothing@0.15  smoothing@0.35  \
0       1 2017-10-16  143.750000  2001900          143.75          143.75   
1       2 2017-10-17  143.429993  2435600          143.70          143.64   
2       3 2017-10-18  143.440002  1734100          143.66          143.57   
3       4 2017-10-19  143.619995  2623100          143.65          143.59   
4       5 2017-10-20  145.350006  3369500          143.91          144.21   

   smoothing@0.55  smoothing@0.75  
0          143.75          143.75  
1          143.57          143.51  
2          143.50          143.46  
3          143.57          143.58  
4          144.55          144.91

Calculate the forecasting value for row 124 (2018-04-16) as below

In [351]:
# Insert Row 124
df['smoothing@0.15'][124] = round(0.15 * df.Close[123] + (1 - 0.15) * df['smoothing@0.15'][123], 2)

df['smoothing@0.35'][124] = round(0.35 * df.Close[123] + (1 - 0.35) * df['smoothing@0.35'][123], 2)

df['smoothing@0.55'][124] = round(0.55 * df.Close[123] + (1 - 0.55) * df['smoothing@0.55'][123], 2)

df['smoothing@0.75'][124] = round(0.75 * df.Close[123] + (1 - 0.75) * df['smoothing@0.75'][123], 2)


Append the above values into the dataframe row as below

In [346]:
df = df.append(pd.Series([125,'2018-04-16 00:00:00',0,0, 145.49, 145.69, 146.0, 146.11], index=df.columns ), ignore_index=True)

Rename the Dataframe Columms for convience

In [366]:
df15 = df['smoothing@0.15']
df35 = df['smoothing@0.35']
df55 = df['smoothing@0.55']
df75 = df['smoothing@0.75']

### Mean Square Error calculation

The measure of mean squared error requires a target of prediction or estimation along with a predictor or estimator which is said to be the function of the given data. MSE is defined as the average of squares of the "errors". 

MSE = 1/n n∑i = (Xi^−Xi)**2

In [367]:
mse = [(close[i] - df15[i])**2 for i in range(0,len(close))]
print("Mean square error at alpha 0.15 = ",np.mean(mse))

mse1 = [(close[i] - df35[i])**2 for i in range(0,len(close))]
print("Mean square error at alpha 0.35 = ",np.mean(mse1))

mse2 = [(close[i] - df55[i])**2 for i in range(0,len(close))]
print("Mean square error at alpha 0.55 = ",np.mean(mse2))

mse3 = [(close[i] - df75[i])**2 for i in range(0,len(close))]
print("Mean square error at alpha 0.75 = ",np.mean(mse3))


Mean square error at alpha 0.15 =  5.714341287436218
Mean square error at alpha 0.35 =  1.9047011156620248
Mean square error at alpha 0.55 =  0.685191634371702
Mean square error at alpha 0.75 =  0.18477841808137846


In [368]:
df.tail()

Period                 Date       Close   Volume  smoothing@0.15  \
120     121  2018-04-10 00:00:00  145.630005  2880400          145.17   
121     122  2018-04-11 00:00:00  144.279999  1953100          145.04   
122     123  2018-04-12 00:00:00  146.470001  2327600          145.25   
123     124  2018-04-13 00:00:00  146.119995  1588500          145.38   
124     125  2018-04-16 00:00:00    0.000000        0          145.49   

     smoothing@0.35  smoothing@0.55  smoothing@0.75  
120          144.42          144.60          144.98  
121          144.37          144.42          144.45  
122          145.11          145.55          145.97  
123          145.46          145.86          146.08  
124          145.69          146.00          146.11

### Problem 1 : Conclusion 

1) Mean Square error of alpha at 0.75 is the minimum at 0.1847. Hence the forecasting closing value for stock price at honeywell on 2018-04-16  is **146.11**

2) The forecasted value at time i+1 is based on the value at time i, and the forecasted value at time i (and so indirectly on all the previous time values). In particular, for some α where 0 ≤ α ≤ 1.